# Generated by Django 5.2.14 on 2026-08-05 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField()),
                ('status', models.TextField(default='pending')),
                ('date', models.DateTimeField()),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('servicetype', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='SERVICEPROVIDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.serviceprovider'),
        ),
    ]
