# Generated by Django 5.2.14 on 2026-08-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='12345', max_length=100),
            preserve_default=False,
        ),
    ]
