# Generated by Django 5.2.14 on 2026-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Problem',
            field=models.TextField(default='hellllllllooooooooooooo'),
            preserve_default=False,
        ),
    ]
