# Generated by Django 5.2.14 on 2026-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_request_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
