# Generated by Django 5.2.14 on 2026-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_request_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
