# Generated by Django 5.2.14 on 2026-09-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_serviceprovider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='polarity',
            field=models.CharField(default='positive', max_length=100),
            preserve_default=False,
        ),
    ]
